version: '3'
services:
  patient:
    environment:
        - CLIENT_NOTE_BASE_URL=http://notes:8082/
        - CLIENT_ASSESSMENT_BASE_URL=http://assessment:8083/assessment
    build:
        context: ./patient/
        dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    
  notes:
    environment:
        - CLIENT_PATIENT_BASE_URL=http://patient:8081/
    build:
        context: ./notes/
        dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    
  assessment:
    build:
        context: ./assessment/
        dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
 
    
  

